# Generated by Django 5.1.3 on 2024-11-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Web", "Web"),
                            ("Tech", "Tech"),
                            ("Business", "Business"),
                            ("Health", "Health"),
                            ("Opinion", "Opinion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
