# Generated by Django 5.1.3 on 2024-11-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image_url",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="press_images/"),
        ),
    ]
