# Generated by Django 5.1.3 on 2024-11-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0006_rename_category_itemcategory_alter_resume_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("research", "Research and Consultancy"),
                            ("analytics", "Data Analytics and Reporting"),
                            ("infrastructure", "Data Infrastructure Development"),
                            ("planning", "Strategic Planning"),
                            ("stem", "STEM Education Promotion"),
                            ("training", "Training and Capacity Building"),
                            ("technology", "Technology Import and Supply"),
                            ("software", "Customized Software Solutions"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
