# Generated by Django 5.1.3 on 2024-11-07 08:49

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0007_portfolio"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="client",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="project_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="project_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
        ),
    ]
