# Generated by Django 5.1.3 on 2024-11-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0008_portfolio_client_portfolio_project_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("image", models.ImageField(upload_to="team_images/")),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
