# Generated by Django 5.1.3 on 2024-11-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0010_testimonial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="facebook_url",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="twitter_url",
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="author_title",
            field=models.CharField(max_length=100),
        ),
    ]
