# Generated by Django 5.1.3 on 2024-11-07 13:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0011_remove_testimonial_facebook_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="quote",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="quote"),
        ),
    ]
