# Generated by Django 5.1.3 on 2024-11-07 13:22

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0013_alter_item_description_alter_post_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="ontent"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="bio",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Bio "),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="quote",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Quote "),
        ),
    ]
