# Generated by Django 5.1.3 on 2024-11-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0017_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
