# Generated by Django 5.1.3 on 2024-11-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0018_article_is_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="is_featured",
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("news_updates", "News & Updates"),
                    ("educational", "Educational Content"),
                    ("promotions", "Promotions & Offers"),
                    ("thought_leadership", "Thought Leadership & Insights"),
                    ("community", "Community & Engagement"),
                    ("lifestyle", "Lifestyle & Inspiration"),
                    ("curated", "Curated Content & Roundups"),
                    ("behind_scenes", "Behind-the-Scenes & Company Culture"),
                    ("seasonal", "Seasonal & Thematic Newsletters"),
                    ("feedback", "Feedback & Surveys"),
                ],
                max_length=50,
            ),
        ),
    ]
