# Generated by Django 5.1.3 on 2024-11-08 20:06

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0019_remove_article_is_featured_alter_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("news_updates", "News & Updates"),
                    ("educational", "Educational Content"),
                    ("promotions", "Promotions & Offers"),
                    ("thought_leadership", "Thought Leadership & Insights"),
                    ("community", "Community & Engagement"),
                    ("lifestyle", "Lifestyle & Inspiration"),
                    ("curated", "Curated Content & Roundups"),
                    ("behind_scenes", "Behind-the-Scenes & Company Culture"),
                    ("seasonal", "Seasonal & Thematic Newsletters"),
                    ("feedback", "Feedback & Surveys"),
                    ("sport", "Sports & Entertainment"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="article",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
