# Generated by Django 5.1.3 on 2024-11-13 08:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0020_article_is_featured_alter_article_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="NewsletterSubscription",
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="ontent"),
        ),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
